title = "The Rust Programming Language"
author = "Steve Klabnik and Carol Nichols, with Contributions from the Rust Community"
source = "src"

[output.html]
destination = "book"
theme = "theme"
additional-css = ["theme/custom.css"]
additional-js = ["theme/custom.js"]
